"use client";

import { Montserrat, League_Spartan } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/LayoutComponents/Navbar";
import { Footer } from "@/components/LayoutComponents/Footer";
import useLenis from "@/hooks/useLenis";

// Load Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

// Load League Spartan
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-league-spartan",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  useLenis();

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${leagueSpartan.variable} font-league bg-[#090909] text-white overflow-x-hidden`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
